---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
matrix:
  include:
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - rvm: 2.4
    env: PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  email: false
